In [93]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors

In [94]:
scalar= torch.tensor(7)

In [95]:
scalar

tensor(7)

In [96]:
scalar.ndim

0

only for scalar does item work

In [97]:
scalar.item()

7

In [98]:
vector = torch.tensor([7,6])

In [99]:
vector

tensor([7, 6])

how many square bracket is the dimension of tensor

In [100]:
vector.ndim

1

In [101]:
vector.shape

torch.Size([2])

In [102]:
vector[1]

tensor(6)

In [103]:
#TENSORS
#this is shape
TENSOR = torch.tensor([[[1,2],[4,5],[7,8]]])
#torch.Size([1, 3, 2])
#[[[1,2],[4,5],[7,8]]]<-----this bracket has 1 element
#[[1,2],[4,5],[7,8]]<----- this bracket has 3 elements
#all the elements inside the last bracket has 2 elements

In [104]:
TENSOR

tensor([[[1, 2],
         [4, 5],
         [7, 8]]])

In [105]:
TENSOR.shape

torch.Size([1, 3, 2])

In [106]:
TENSOR.ndim

3

RANDOM TENSORS


In [107]:
 random_tensor= torch.rand(1,3,2)
 random_tensor

tensor([[[0.2089, 0.5243],
         [0.4429, 0.5985],
         [0.6232, 0.4104]]])

In [108]:
random_image_size_tensor= torch.rand(size=(3,224,224))
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

Tensors of 0 and 1s

In [109]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [110]:
ones = torch.ones(3,4)

In [111]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [112]:
ones.dtype

torch.float32

Creating a range of tensore and tensors like

In [113]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
range = torch.arange(0,100,10)

In [115]:
range

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [116]:
#tensor like
ten_zeroes = torch.zeros_like(range)

In [117]:
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor data types


Note: Tensor datatypes are one of 3 big issues we run into in pytorch and data science

1.Tensor not right datatype

2.Tensor not right shape

3.Tensor not on the right device

In [124]:
float_tensor = torch.tensor([3,6,9],
                            dtype=None,#data type in tensor
                            device=None,#device tensor is on, diffrent tensor in different device cause issue
                            requires_grad=False)#whether or not to track gradients with this tensors operation

In [126]:
float

float

In [127]:
float_tensor

tensor([3, 6, 9])

In [128]:
float_16_tensor = float_tensor.type(torch.float16)

In [129]:
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [130]:
float_16_tensor*float_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)