In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors

In [4]:
scalar= torch.tensor(7)

In [5]:
scalar

tensor(7)

In [6]:
scalar.ndim

0

only for scalar does item work

In [7]:
scalar.item()

7

In [8]:
vector = torch.tensor([7,6])

In [9]:
vector

tensor([7, 6])

how many square bracket is the dimension of tensor

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [12]:
vector[1]

tensor(6)

In [13]:
#TENSORS
#this is shape
TENSOR = torch.tensor([[[1,2],[4,5],[7,8]]])
#torch.Size([1, 3, 2])
#[[[1,2],[4,5],[7,8]]]<-----this bracket has 1 element
#[[1,2],[4,5],[7,8]]<----- this bracket has 3 elements
#all the elements inside the last bracket has 2 elements

In [14]:
TENSOR

tensor([[[1, 2],
         [4, 5],
         [7, 8]]])

In [15]:
TENSOR.shape

torch.Size([1, 3, 2])

In [16]:
TENSOR.ndim

3

RANDOM TENSORS


In [17]:
 random_tensor= torch.rand(1,3,2)
 random_tensor

tensor([[[0.5758, 0.6129],
         [0.0482, 0.7223],
         [0.5394, 0.4779]]])

In [18]:
random_image_size_tensor= torch.rand(size=(3,224,224))
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

Tensors of 0 and 1s

In [19]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
ones = torch.ones(3,4)

In [21]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

Creating a range of tensore and tensors like

In [23]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
range = torch.arange(0,100,10)

In [25]:
range

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [26]:
#tensor like
ten_zeroes = torch.zeros_like(range)

In [27]:
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor data types


Note: Tensor datatypes are one of 3 big issues we run into in pytorch and data science

1.Tensor not right datatype

2.Tensor not right shape

3.Tensor not on the right device

In [28]:
float_tensor = torch.tensor([3,6,9],
                            dtype=None,#data type in tensor
                            device=None,#device tensor is on, diffrent tensor in different device cause issue
                            requires_grad=False)#whether or not to track gradients with this tensors operation

In [29]:
float

float

In [30]:
float_tensor

tensor([3, 6, 9])

In [31]:
float_16_tensor = float_tensor.type(torch.float16)

In [32]:
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [33]:
float_16_tensor*float_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

Lesson 2

In [34]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)

In [35]:
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [36]:
float_tensor*int_32_tensor

tensor([ 9, 36, 81])

Getting information from tensors

1.Tensor not right datatype- to get datatype from a tensor, use tensor.dtype

2.Tensor not right shape- to get shape, use tensor.shape

3.Tensor not on the right device- to get device from a tensor, use tensor.device

In [37]:
some_tensor = torch.rand(3,4)

In [38]:
some_tensor

tensor([[0.1426, 0.7080, 0.6202, 0.6515],
        [0.3950, 0.2464, 0.0304, 0.2241],
        [0.3820, 0.4530, 0.0938, 0.3383]])

Finding out details about the tensors

In [39]:
some_tensor.dtype

torch.float32

In [40]:
some_tensor.shape

torch.Size([3, 4])

In [41]:
some_tensor.device

device(type='cpu')

Manipulation Tensors (Tensor operations)

Tensor operations include:

1. Addition

2. Subtraction

3. Multiplication (element wise)

4. Division

5. Matrix multiplication

In [42]:
new_tensor= torch.tensor([1,2,3])
new_tensor+10

tensor([11, 12, 13])

In [43]:
new_tensor*10

tensor([10, 20, 30])

In [44]:
new_tensor-10

tensor([-9, -8, -7])

In [45]:
 #in built multipy function
 torch.mul(new_tensor,10)

tensor([10, 20, 30])

In [46]:
torch.add(new_tensor,10)

tensor([11, 12, 13])

2 main ways of performing multiplication in neural network and deep learning

1. Element wise multiplication

2. Matrix multiplication

There are two main rules that performing matrix mutliplication needs to satisfy:

1. The inner dimensions must match

  * (3,2) @ (2,3) wont work

  * (2,3) @ (3,2) will work

  * (3,2) @ (2,3) will work

2. The resulting matrix have the shape of the outer matrix





In [47]:
#Element wise multiplication
tensor = torch.tensor([2,3,4])
tensor

tensor([2, 3, 4])

In [48]:
element_wise_multiplicaton = tensor*tensor
element_wise_multiplicaton

tensor([ 4,  9, 16])

In [49]:
matrix_wise_multiplication = torch.matmul(tensor,tensor)
matrix_wise_multiplication

tensor(29)

In [50]:
new_matrix= torch.mm(torch.rand(2,3),torch.rand(3,4)) #mm is same as matmul

In [51]:
new_matrix

tensor([[0.3257, 1.0874, 0.5414, 0.9458],
        [0.6837, 0.9348, 0.6819, 0.8981]])

One of the most common errors in deep learning: Shape errors

To fix the tensor shape issues, we can manipulate the shape of one of our tensors using a transpose



In [52]:
tensor_A = torch.rand(3,4)
tensor_A,tensor_A.shape

(tensor([[0.7572, 0.9554, 0.6812, 0.0398],
         [0.8546, 0.0842, 0.7372, 0.7448],
         [0.5546, 0.0226, 0.6011, 0.6970]]),
 torch.Size([3, 4]))

In [53]:
tensor_A.T,tensor_A.T.shape

(tensor([[0.7572, 0.8546, 0.5546],
         [0.9554, 0.0842, 0.0226],
         [0.6812, 0.7372, 0.6011],
         [0.0398, 0.7448, 0.6970]]),
 torch.Size([4, 3]))

LESSON 3

TENSOR AGGREGATION

Finding the min, max, mean, sum,etc

In [54]:
x = torch.arange(0,100,9)
x

tensor([ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 99])

In [55]:
#Minimum
torch.min(x)

tensor(0)

In [56]:
#Max
torch.max(x)

tensor(99)

In [57]:
#sum
torch.sum(x),x.sum()

(tensor(594), tensor(594))

In [58]:
#mean

#input dtype should be either floating point or complex dtypes but not long
torch.mean(x.type(torch.float32)),(x.type(torch.float32)).mean()

(tensor(49.5000), tensor(49.5000))

Finding the position of min and max

In [59]:
# position of minimum value
x.argmin(),torch.argmin(x)

(tensor(0), tensor(0))

In [60]:
#position of maximum value
x.argmax(),torch.argmax(x)

(tensor(11), tensor(11))

LESSON 4

Reshaping,viewing, stacking, squeezing, unsqueezing and permuting tensors

Reshaping = reshapes an input tensor to a defined shape

View = Return a view of input tensor of certain shape but keep the same memory as the original tensor

Stacking = combine multiple tensors on top of each other(vstack) or side by side (hstack)

Squeeze= removes all `1` dimension from a *tensor*

Unsqueeze = add a `1` dimension to a target tensor

Permute = return a view of the input with dimensions permuted (swapped) in a certain way

In [61]:
new_variable_x= torch.arange(1,13)
new_variable_x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [62]:
#reshape helps to change the dimension of tensor form certain kind to certain kind

new_variable_x.reshape(2,6),new_variable_x.shape

(tensor([[ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12]]),
 torch.Size([12]))

In [63]:
#change the view
z= new_variable_x.view(3,4)
z,z.shape

(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]),
 torch.Size([3, 4]))

In [64]:
#changing z changes new_variable_x because  a view of tensor shares the same memory as the original input
z[:,0]=5
z,new_variable_x

(tensor([[ 5,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 5, 10, 11, 12]]),
 tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  5, 10, 11, 12]))

In [65]:
#Stack tensors on top of each other
x_stacked = torch.stack([new_variable_x,new_variable_x,new_variable_x,new_variable_x],dim=1)
x_stacked

tensor([[ 5,  5,  5,  5],
        [ 2,  2,  2,  2],
        [ 3,  3,  3,  3],
        [ 4,  4,  4,  4],
        [ 5,  5,  5,  5],
        [ 6,  6,  6,  6],
        [ 7,  7,  7,  7],
        [ 8,  8,  8,  8],
        [ 5,  5,  5,  5],
        [10, 10, 10, 10],
        [11, 11, 11, 11],
        [12, 12, 12, 12]])

In [66]:
#squeeze
y= torch.rand(1,1,3)
y,y.shape
sqz= y.squeeze()


In [67]:
sqz,sqz.shape
#all one dimensions removed

(tensor([0.6784, 0.9464, 0.0499]), torch.Size([3]))

In [68]:
#unsqueeze- adds single dimension at specific dim
sqz.unsqueeze(0).shape,sqz.unsqueeze(1).shape
#at 0th index 1 is added,#at 1th index 1 is added

(torch.Size([1, 3]), torch.Size([3, 1]))

In [69]:
#torch.permute
#shares the same memory as the variable
rand_x = torch.rand(size=(224,224,3))

permuted_x = rand_x.permute(2,0,1)

print(f"Previous shape:{rand_x.shape}")
print(f"New shape:{permuted_x.shape}")

Previous shape:torch.Size([224, 224, 3])
New shape:torch.Size([3, 224, 224])


In [70]:
rand_x[0,0,0] =72818
rand_x[0,0,0],permuted_x[0,0,0]

(tensor(72818.), tensor(72818.))

Indexing(selecting data from tensors)   

In [71]:
#Create a tensor
x=torch.arange(1,13).reshape(1,4,3)
x,x.shape

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9],
          [10, 11, 12]]]),
 torch.Size([1, 4, 3]))

In [72]:
x[0][2]

tensor([7, 8, 9])

In [73]:
x[0,2,2]

tensor(9)

In [74]:
#getting all values of 0th and 1st dimension but only index 1 of 2nd dimension
x[:,:,1]

tensor([[ 2,  5,  8, 11]])

In [75]:
x[:,1,1]

tensor([5])

In [76]:
x[0,:,2]

tensor([ 3,  6,  9, 12])

Pytorch and Numpy

In [77]:
#NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0,13.0)# data type is float32
tensor= torch.from_numpy(array)
array,tensor

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        dtype=torch.float64))

In [78]:
#tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Reproducibility
-trying to takeout randomness out of random

we use random seed to reduce the randomness in neural networks

In [79]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

random_tensor_A,random_tensor_B,random_tensor_A==random_tensor_B

(tensor([[9.6691e-01, 1.4065e-01, 2.1694e-03, 7.9459e-01],
         [7.3971e-01, 8.3051e-01, 2.6173e-01, 2.8321e-01],
         [5.6947e-01, 8.7629e-01, 7.1776e-04, 4.6848e-01]]),
 tensor([[0.4108, 0.4770, 0.8799, 0.5418],
         [0.6672, 0.0908, 0.7812, 0.4766],
         [0.4569, 0.2317, 0.8479, 0.5855]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [80]:
RANDOM_SEED =10
torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3,4)

random_tensor_c,random_tensor_d,random_tensor_c==random_tensor_d

(tensor([[0.4581, 0.4829, 0.3125, 0.6150],
         [0.2139, 0.4118, 0.6938, 0.9693],
         [0.6178, 0.3304, 0.5479, 0.4440]]),
 tensor([[0.4581, 0.4829, 0.3125, 0.6150],
         [0.2139, 0.4118, 0.6938, 0.9693],
         [0.6178, 0.3304, 0.5479, 0.4440]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

Running tensors and Pytorch objects on the GPUs(and making faster computations)

GPU= faster thanks to CUDA hardware

Getting GPU:
1. Google Collab
2. Own GPU- buy GPU
3. Cloud computing

In [82]:
#check for GPU access with Pytorch
torch.cuda.is_available()

True

In [84]:
#setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [85]:
torch.cuda.device_count()

1

Putting a tensor(and models) on the GPU

In [90]:
#default cpu
tensor= torch.tensor([1,2,3])
tensor,tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [92]:
#using gpu
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [93]:
tensor_on_cpu = tensor.to("cpu")

In [95]:
tensor_on_cpu.device

device(type='cpu')

In [98]:
array = tensor_on_cpu.numpy()# array= tensor_on_gpu.cpu().numpy()

In [97]:
array

array([1, 2, 3])