In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors

In [3]:
scalar= torch.tensor(7)

In [4]:
scalar

tensor(7)

In [5]:
scalar.ndim

0

only for scalar does item work

In [6]:
scalar.item()

7

In [7]:
vector = torch.tensor([7,6])

In [8]:
vector

tensor([7, 6])

how many square bracket is the dimension of tensor

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
vector[1]

tensor(6)

In [12]:
#TENSORS
#this is shape
TENSOR = torch.tensor([[[1,2],[4,5],[7,8]]])
#torch.Size([1, 3, 2])
#[[[1,2],[4,5],[7,8]]]<-----this bracket has 1 element
#[[1,2],[4,5],[7,8]]<----- this bracket has 3 elements
#all the elements inside the last bracket has 2 elements

In [13]:
TENSOR

tensor([[[1, 2],
         [4, 5],
         [7, 8]]])

In [14]:
TENSOR.shape

torch.Size([1, 3, 2])

In [15]:
TENSOR.ndim

3

RANDOM TENSORS


In [16]:
 random_tensor= torch.rand(1,3,2)
 random_tensor

tensor([[[0.5158, 0.4031],
         [0.1985, 0.5773],
         [0.3264, 0.1460]]])

In [17]:
random_image_size_tensor= torch.rand(size=(3,224,224))
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

Tensors of 0 and 1s

In [18]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
ones = torch.ones(3,4)

In [20]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

Creating a range of tensore and tensors like

In [22]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
range = torch.arange(0,100,10)

In [24]:
range

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [25]:
#tensor like
ten_zeroes = torch.zeros_like(range)

In [26]:
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor data types


Note: Tensor datatypes are one of 3 big issues we run into in pytorch and data science

1.Tensor not right datatype

2.Tensor not right shape

3.Tensor not on the right device

In [27]:
float_tensor = torch.tensor([3,6,9],
                            dtype=None,#data type in tensor
                            device=None,#device tensor is on, diffrent tensor in different device cause issue
                            requires_grad=False)#whether or not to track gradients with this tensors operation

In [28]:
float

float

In [29]:
float_tensor

tensor([3, 6, 9])

In [30]:
float_16_tensor = float_tensor.type(torch.float16)

In [31]:
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [32]:
float_16_tensor*float_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

Lesson 2

In [33]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)

In [34]:
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [35]:
float_tensor*int_32_tensor

tensor([ 9, 36, 81])

Getting information from tensors

1.Tensor not right datatype- to get datatype from a tensor, use tensor.dtype

2.Tensor not right shape- to get shape, use tensor.shape

3.Tensor not on the right device- to get device from a tensor, use tensor.device

In [36]:
some_tensor = torch.rand(3,4)

In [37]:
some_tensor

tensor([[0.3876, 0.5868, 0.6333, 0.3833],
        [0.3327, 0.0454, 0.5752, 0.0517],
        [0.6395, 0.0920, 0.1964, 0.8405]])

Finding out details about the tensors

In [38]:
some_tensor.dtype

torch.float32

In [39]:
some_tensor.shape

torch.Size([3, 4])

In [40]:
some_tensor.device

device(type='cpu')

Manipulation Tensors (Tensor operations)

Tensor operations include:

1. Addition

2. Subtraction

3. Multiplication (element wise)

4. Division

5. Matrix multiplication

In [41]:
new_tensor= torch.tensor([1,2,3])
new_tensor+10

tensor([11, 12, 13])

In [42]:
new_tensor*10

tensor([10, 20, 30])

In [43]:
new_tensor-10

tensor([-9, -8, -7])

In [44]:
 #in built multipy function
 torch.mul(new_tensor,10)

tensor([10, 20, 30])

In [45]:
torch.add(new_tensor,10)

tensor([11, 12, 13])

2 main ways of performing multiplication in neural network and deep learning

1. Element wise multiplication

2. Matrix multiplication

There are two main rules that performing matrix mutliplication needs to satisfy:

1. The inner dimensions must match

  * (3,2) @ (2,3) wont work

  * (2,3) @ (3,2) will work

  * (3,2) @ (2,3) will work

2. The resulting matrix have the shape of the outer matrix





In [46]:
#Element wise multiplication
tensor = torch.tensor([2,3,4])
tensor

tensor([2, 3, 4])

In [47]:
element_wise_multiplicaton = tensor*tensor
element_wise_multiplicaton

tensor([ 4,  9, 16])

In [48]:
matrix_wise_multiplication = torch.matmul(tensor,tensor)
matrix_wise_multiplication

tensor(29)

In [49]:
new_matrix= torch.mm(torch.rand(2,3),torch.rand(3,4)) #mm is same as matmul

In [50]:
new_matrix

tensor([[0.5965, 0.5801, 0.6037, 0.9344],
        [0.3858, 0.5206, 0.4184, 0.6077]])

One of the most common errors in deep learning: Shape errors

To fix the tensor shape issues, we can manipulate the shape of one of our tensors using a transpose



In [51]:
tensor_A = torch.rand(3,4)
tensor_A,tensor_A.shape

(tensor([[0.9581, 0.4503, 0.2711, 0.4852],
         [0.7348, 0.0759, 0.9254, 0.2380],
         [0.0829, 0.3298, 0.5600, 0.8030]]),
 torch.Size([3, 4]))

In [52]:
tensor_A.T,tensor_A.T.shape

(tensor([[0.9581, 0.7348, 0.0829],
         [0.4503, 0.0759, 0.3298],
         [0.2711, 0.9254, 0.5600],
         [0.4852, 0.2380, 0.8030]]),
 torch.Size([4, 3]))

LESSON 3

TENSOR AGGREGATION

Finding the min, max, mean, sum,etc

In [53]:
x = torch.arange(0,100,9)
x

tensor([ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 99])

In [55]:
#Minimum
torch.min(x)

tensor(0)

In [57]:
#Max
torch.max(x)

tensor(99)

In [68]:
#sum
torch.sum(x),x.sum()

(tensor(594), tensor(594))

In [70]:
#mean

#input dtype should be either floating point or complex dtypes but not long
torch.mean(x.type(torch.float32)),(x.type(torch.float32)).mean()

(tensor(49.5000), tensor(49.5000))

Finding the position of min and max

In [74]:
# position of minimum value
x.argmin(),torch.argmin(x)

(tensor(0), tensor(0))

In [75]:
#position of maximum value
x.argmax(),torch.argmax(x)

(tensor(11), tensor(11))